eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://172.26.122.138:8761/eureka/eureka
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
spring:
  application:
    name: eureka-provider
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.26.122.140:3306/ide_poc?autoreconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
server:
  port: 8081

#mybatis:
#  type-aliases-package: cn.caber.springcloudeurekaprovider.po
#  mapper-locations: classpath:mapper/*Dao.xml