eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gateway
  cloud:
      gateway:
#        discovery:
#          locator:
#            enabled: true
#            lowerCaseServiceId: true
        routes:
#        - id: abc
#          uri: http://localhost:8081/abc
#          predicates:
#          - Path=/abc/**
        - id: hello
          uri: lb://eureka-provider
          predicates:
          - Path=/hello/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@ipKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 2 #限流桶的大小
  redis:
      host: localhost
      port: 6379
      database: 1


server:
  port: 8900




hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
#          thread:
#            timeoutInMilliseconds: 1000
#      circuitBreaker:
#        requestVolumeThreshold: 3 #失败的次数
#        sleepWindowInMilliseconds: 10000  #熔断器开启的时间
#        forceOpen: true #强制打开熔断器，测试使用





