spring:
  application:
    name: consul-client
  cloud:
    consul:
      host: 172.16.101.115
      port: 8500
      discovery:
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s


