spring:
  application:
    name: zuul-service

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
  routes:
    api:
        path: /**
        serviceId: ribbon-consumer
  ratelimit:
      enabled: true
      behind-proxy: true
      policy-list:
        ribbon-consumer:
          - limit: 10
            refresh-interval: 60
            type:
              - user
              - origin
              - url

qps: 1