server:
  port: 9002

spring:
  application:
    name: springcloud-zookeeper-server
  cloud:
    zookeeper:
      connect-string: 192.168.1.141:2181
      discovery:
        enabled: true
        register: true



